### ISSUE TITLE
Docker: Running start.sh fails with "st2: command not found"

### ISSUE THREAD

**Issue by withrocks** [StackStorm/st2express#56]
Repro: 

```bash
sudo docker build -t st2 .
sudo docker run -it st2
```
Then, running the following inside the container:
```bash
/root/st2/start.sh 
```
results in:
```bash
ERROR!
Something went wrong, st2 failed to start
Command output:
/root/st2/start.sh: line 23: st2: command not found
```
Further:
```bash
root@3e4d78dff750:/# which st2
root@3e4d78dff750:/# find / -name st2 | xargs file
/var/log/st2:       directory 
/usr/share/doc/st2: directory 
/etc/st2:           directory 
/etc/sudoers.d/st2: ASCII text
/root/st2:          directory 
```

**Comment by Kami** [comment]
It looks like that the CLI for some reason didn't get installed with the st2_deploy.sh script.

I will look into it and try to reproduce the issue.

**Comment by Kami** [comment]
@withrocks I tried to reproduce it, but I couldn't.

I believe there was a temporary network or a similar issue which caused the CLI to not be installed. 

I just merged #57. Before that, `docker build` command would proceed normally and not fail, even if `st2_deploy.sh` didn't finish successfully.

Can you please pull down latest master and try rebuilding the image (`docker rmi st2 ; docker build --no-cache -t st2 .`) and if the build command fails or the issue still persists, please gist the `docker build` logs and we will have a look.

**Comment by Kami** [comment]
@withrocks I believe this is related to this issue https://github.com/StackStorm/st2/pull/1543.

As a temporary workaround, you can get it to work by using latest working version (`0.9.0`) - you can update `Dockerfile` and replace 0.9.2 with 0.9.0.

In the mean time we are also working on new release (v0.9.3) which fixes this issue. I will let you know once that release is out.

**Comment by withrocks** [comment]
@Kami Thanks for looking into this. 

I tried version 0.9.0 but it does actually also fail for me, but with this error:

```bash
Command /opt/openstack/mistral/.venv/bin/python -c "import setuptools, tokenize;__file__='/opt/openstack/mistral/.venv/build/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-0c2E92-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/openstack/mistral/.venv/include/site/python2.7 failed with error code 1 in /opt/openstack/mistral/.venv/build/cryptography 
```
Repro: 
* I installed docker from get.docker.com on a clean ubuntu/trusty64 vagrant box, then ran this:

```bash
cd st2express/docker
sed -i Dockerfile 's/0.9.2/0.9.0/'
sudo docker build -t st2 . | tee -a st2.build.log
```
The log file can be found here: https://gist.github.com/withrocks/f1e28fd289ab161e8947

**Comment by Kami** [comment]
Hm, looks like it failed to install one of the mistral dependencies. It could be that the base box / our Dockerfile is missing some build tool / library package.

Can you please also gist `/root/.pip/pip.log` file.

**Comment by DoriftoShoes** [comment]
The client issue has now been resolved for 0.9.2.  You should be able install that version without issue now.

**Comment by withrocks** [comment]
I went back to 0.9.2 as per @DoriftoShoes suggestion, but I still got that Python/gcc issue. The pip.log points to a gcc compilation error: ```error: command 'x86_64-linux-gnu-gcc' failed with exit status 4```

See the full pip.log here:
https://gist.github.com/anonymous/06aaaa79352c4fd66b93

**Comment by Kami** [comment]
Yeah, as I have thought, it looks like it failed to build a dependency.

Judging by the error (x86_64-linux-gnu-gcc: internal compiler error: Killed (program cc1)) it seems like a memory issue - are you sure that the host you are trying to run this docker container one has enough free memory available?

**Comment by withrocks** [comment]
@Kami Thanks, that was the issue.

**Comment by Kami** [comment]
Np and glad it got resolved.
